# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tachiBackup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11tachiBackup.proto\x12\x0fTachiyomiBackup\";\n\x06\x42\x61\x63kup\x12\x31\n\x0b\x62\x61\x63kupManga\x18\x01 \x03(\x0b\x32\x1c.TachiyomiBackup.BackupManga\"O\n\x0b\x42\x61\x63kupManga\x12\r\n\x05title\x18\x03 \x01(\t\x12\x31\n\x08tracking\x18\x12 \x03(\x0b\x32\x1f.TachiyomiBackup.BackupTracking\"Y\n\x0e\x42\x61\x63kupTracking\x12\x0e\n\x06syncId\x18\x01 \x01(\x05\x12\x11\n\tlibraryId\x18\x02 \x01(\x03\x12\x0f\n\x07mediaId\x18\x03 \x01(\x05\x12\x13\n\x0btrackingUrl\x18\x04 \x01(\tb\x06proto3')



_BACKUP = DESCRIPTOR.message_types_by_name['Backup']
_BACKUPMANGA = DESCRIPTOR.message_types_by_name['BackupManga']
_BACKUPTRACKING = DESCRIPTOR.message_types_by_name['BackupTracking']
Backup = _reflection.GeneratedProtocolMessageType('Backup', (_message.Message,), {
  'DESCRIPTOR' : _BACKUP,
  '__module__' : 'tachiBackup_pb2'
  # @@protoc_insertion_point(class_scope:TachiyomiBackup.Backup)
  })
_sym_db.RegisterMessage(Backup)

BackupManga = _reflection.GeneratedProtocolMessageType('BackupManga', (_message.Message,), {
  'DESCRIPTOR' : _BACKUPMANGA,
  '__module__' : 'tachiBackup_pb2'
  # @@protoc_insertion_point(class_scope:TachiyomiBackup.BackupManga)
  })
_sym_db.RegisterMessage(BackupManga)

BackupTracking = _reflection.GeneratedProtocolMessageType('BackupTracking', (_message.Message,), {
  'DESCRIPTOR' : _BACKUPTRACKING,
  '__module__' : 'tachiBackup_pb2'
  # @@protoc_insertion_point(class_scope:TachiyomiBackup.BackupTracking)
  })
_sym_db.RegisterMessage(BackupTracking)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BACKUP._serialized_start=38
  _BACKUP._serialized_end=97
  _BACKUPMANGA._serialized_start=99
  _BACKUPMANGA._serialized_end=178
  _BACKUPTRACKING._serialized_start=180
  _BACKUPTRACKING._serialized_end=269
# @@protoc_insertion_point(module_scope)
